name: Deploy to web hosting
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v4

      - name: ğŸ— Setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: âš™ï¸ Install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: ğŸ›  Build
        run: npm run build

      - name: ğŸ“‚ Upload build (to artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ndfl-calculator-front
          path: ./dist/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ–¥ Download built WEB (to artifacts)
        uses: actions/download-artifact@v4
        with:
          name: ndfl-calculator-front

      - name: ğŸ“‚ Upload static files to the server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./
          remoteDir: ./
          options: --exclude .htaccess --exclude robots.txt --delete --delete-first --ascii